# Site settings
title: CPH Intern Team
description: CPH Intern Team Tutorials
# baseurl: "/particle" # the subpath of your site, e.g. /blog
baseurl: "/jekyll-particle-demo"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "https://moltenkaizen.github.io"

# User settings
username: CPH Intern Team
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

strict_front_matter: True

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
